# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import registration
import authorization



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.objects_to_del = []
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        font = QtGui.QFont()
        font.setFamily("Parchment")
        self.label.setFont(font)
        
        self.label.setStyleSheet("background-color: rgb(189, 210, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 90, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(41)
        self.label_2.setFont(font)
        
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 230, 381, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-width: 4px;\n"
"    border-style: solid;\n"
"    border-radius: 18px;\n"
"    border-color: black;\n"
"    background-color: rgb(189, 210, 255);\n"
"    font-size: 35px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    font-size: 38px;\n"
"    background-color: rgb(170, 183, 255);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 340, 381, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-width: 4px;\n"
"    border-style: solid;\n"
"    border-radius: 18px;\n"
"    border-color: black;\n"
"    background-color: rgb(189, 210, 255);\n"
"    font-size: 35px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    font-size: 38px;\n"
"    background-color: rgb(170, 183, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 450, 381, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-width: 4px;\n"
"    border-style: solid;\n"
"    border-radius: 18px;\n"
"    border-color: black;\n"
"    background-color: rgb(189, 210, 255);\n"
"    font-size: 35px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    font-size: 38px;\n"
"    background-color: rgb(170, 183, 255);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setCursor(QtCore.Qt.PointingHandCursor)
        self.MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(self.MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

        self.objects_to_del.extend((self.label, self.label_2, self.pushButton, self.pushButton_2, self.pushButton_3))
        self.add_signals()

    def destroing(self):
        for obj in self.objects_to_del:
            obj.deleteLater()
        self.objects_to_del = []

    def registartion_page(self):
        self.destroing()
        ui_2 = registration.Ui_MainWindow()
        ui_2.setupUi(self.MainWindow)

    def auth_page(self):
        self.destroing()
        ui_2 = authorization.Ui_MainWindow()
        ui_2.setupUi(self.MainWindow)

    def exit_program(self):
        self.MainWindow.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Шашки"))
        self.pushButton.setText(_translate("MainWindow", "Регистрация"))
        self.pushButton_2.setText(_translate("MainWindow", "Авторизация"))
        self.pushButton_3.setText(_translate("MainWindow", "Выход"))

    def add_signals(self):
        self.pushButton.clicked.connect(lambda: self.registartion_page())
        self.pushButton_2.clicked.connect(lambda: self.auth_page())
        self.pushButton_3.clicked.connect(lambda: self.exit_program())
        # self.label_4.clicked.connect(lambda: self.show_records())
        # self.label_5.clicked.connect(lambda: self.about_developers())
        # self.label_6.clicked.connect(lambda: self.show_rules())
        # self.label_7.clicked.connect(lambda: self.exit_from_game())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

